DROP TABLE IF EXISTS ListaExercicios CASCADE;
DROP TABLE IF EXISTS Exercicios CASCADE;
DROP TABLE IF EXISTS ExListaEx CASCADE;
DROP TABLE IF EXISTS Alternativas CASCADE;
DROP TABLE IF EXISTS Usuarios CASCADE;
DROP TABLE IF EXISTS Submissoes CASCADE;
DROP TABLE IF EXISTS RespostasAlternativas CASCADE;

DROP SEQUENCE IF EXISTS leid_seq CASCADE;
DROP SEQUENCE IF EXISTS eid_seq CASCADE;
DROP SEQUENCE IF EXISTS subid_seq CASCADE;


CREATE SEQUENCE leid_seq INCREMENT 1 MINVALUE 0 NO MAXVALUE;
CREATE SEQUENCE eid_seq INCREMENT 1 MINVALUE 0 NO MAXVALUE;
CREATE SEQUENCE subid_seq INCREMENT 1 MINVALUE 0 NO MAXVALUE;

CREATE TABLE ListaExercicios(
	LEID INTEGER PRIMARY KEY DEFAULT nextval('leid_seq'),
	titulo VARCHAR(200) NOT NULL,
	tema VARCHAR(200) NOT NULL,
	autor VARCHAR(200) NOT NULL,
	descricao VARCHAR(500) NOT NULL,
	idioma VARCHAR(50) NOT NULL,
	data DATE,
	permuta BOOLEAN NOT NULL DEFAULT FALSE,
	avaliacao INTEGER NOT NULL DEFAULT 0,

	CONSTRAINT unique_titulo_tema_autor UNIQUE (titulo,tema,autor),
	CONSTRAINT check_titulo_tema_autor CHECK (titulo <> '' AND tema <> '' AND autor <> '')
);

CREATE TABLE Exercicios(
	EID INTEGER PRIMARY KEY DEFAULT nextval('eid_seq'),
	titulo VARCHAR(200),
	autor VARCHAR(200),
	enunciado VARCHAR(800) NOT NULL,
	tema VARCHAR(200),
	correta INTEGER NOT NULL,
	permuta BOOLEAN NOT NULL DEFAULT FALSE,

	CONSTRAINT check_enunciado CHECK (enunciado <> '')
);

CREATE TABLE ExListaEx(
	LEID INTEGER NOT NULL,
	EID INTEGER NOT NULL,
	id INTEGER NOT NULL,

	CONSTRAINT pk_leid_eid PRIMARY KEY (LEID,EID),
	CONSTRAINT unique_leid_id UNIQUE (LEID,id),
	CONSTRAINT fk_leid FOREIGN KEY (LEID) REFERENCES ListaExercicios(LEID) ON DELETE CASCADE ON UPDATE CASCADE,
	CONSTRAINT fk_eid FOREIGN KEY (EID) REFERENCES Exercicios(EID) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE Alternativas(
	id INTEGER NOT NULL,
	EID INTEGER NOT NULL,
	texto VARCHAR(500) NOT NULL,

	CONSTRAINT check_texto CHECK (texto <> ''),
	CONSTRAINT pk_id_eid PRIMARY KEY (id,EID),
	CONSTRAINT fk_eid FOREIGN KEY (EID) REFERENCES Exercicios(EID) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE Usuarios(
	nome VARCHAR(200) PRIMARY KEY NOT NULL
);

CREATE TABLE Submissoes(
	subID INTEGER PRIMARY KEY DEFAULT nextval('subid_seq'),
	usuario VARCHAR(200) NOT NULL,
	LEID INTEGER NOT NULL,
	data_hora TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),

	CONSTRAINT fk_leid FOREIGN KEY (LEID) REFERENCES ListaExercicios(LEID) ON DELETE CASCADE ON UPDATE CASCADE,
	CONSTRAINT fk_usuario FOREIGN KEY (usuario) REFERENCES Usuarios(nome) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE RespostasAlternativas(
	subID INTEGER NOT NULL,
	EID INTEGER NOT NULL,
	assinalou INTEGER NOT NULL,
	tentativas INTEGER NOT NULL DEFAULT 0,

	CONSTRAINT pk_subid_eid PRIMARY KEY (subID,EID),
	CONSTRAINT fk_subid FOREIGN KEY (subID) REFERENCES Submissoes(subID) ON DELETE CASCADE ON UPDATE CASCADE,
	CONSTRAINT fk_eid FOREIGN KEY (EID) REFERENCES Exercicios(EID) ON DELETE CASCADE ON UPDATE CASCADE
);